### PR TITLE
refactor: move all sources to src/

### PR DESCRIPTION
**Pull request by rojvv**

### CODE REVIEW

**Review by dcdunkan — COMMENTED** [review]
The reason I left mod.ts outside was for the simple pretty url: https://deno.land/x/grm/mod.ts without the src/. I'm not sure why I left deps.ts out tho.

I'm okay with moving deps.ts. But I think, we should leave mod.ts outside? Or, if its possible to change the subdirectory to src/ in the existing webhook, that'll work too.

**Comment by rojvv** [comment]
Yes, we just update the webhook URL to take it from src/.

**Comment by dcdunkan** [comment]
Oh good. Could you add a minimal readme in src/ that points to this repository? Then we can merge it right away.

**Comment by rojvv** [comment]
I intentionally didn’t include a README there, because not having a README is no longer a dealbreaker in the new deno.land/x.

**Comment by dcdunkan** [comment]
Ah, you're right. OK then.

**Comment by rojvv** [comment]
Also, the GitHub button is some pixels away, so

**Review by dcdunkan — APPROVED** [review]
LGTM

**Pull request merged**
