### PR TITLE
refactor: remove database sessions

### PR DESCRIPTION
**Pull request by rojvv**
1. They are a big obstacle against browser support. (We cannot support browsers if we have them in here.)
2. They are not depending on the internals, meaning that they can be directly moved to an outer module.

### CODE REVIEW

**Comment by dcdunkan** [comment]
I agree with removing it from the main module. But, database sessions are nice. So should we publish it as another module? Maybe you or @watzon can work on this?

**Comment by rojvv** [comment]
@dcdunkan It is going to be super easy.

**Comment by rojvv** [comment]
Just like copying files to another directory.

**Comment by dcdunkan** [comment]
Great. Thanks! Before merging this, can you also remove the example file related to db sessions?

**Pull request merged**
